name: Build all projects

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Portal-App
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build Debug APK with Gradle
        run: ./gradlew assembleDebug

      - name: Create release
        run: |
          gh release delete ${{ env.VERSION }} -y || true
          gh release create ${{ env.VERSION }} -p -t "${{ env.NAME }}" -n "${{ github.event.head_commit.message }}" ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: 'dev-app'
          NAME: 'GDOS Portal App Dev'
          FILES: app/build/outputs/apk/debug/app-debug.apk
